:- begin migration w/ CallitVault.sol (still compiles) 	- migrated all account and balance requirements over to separate CallitVault.sol file 	- integrated callit vault on factory side w/ new ICallitVaul.sol interface 	- updated / fixed all compilation errors 		including interface requirements and additional getter / setters 	- compilation still indeed works and file size as indeed decreased a bit (noted below) 	- … need to keep at it ;)
#================================================#
NEXT:
	- migrate / revert back to CallitLib.sol use (check compile file size)
	… … … … … … 
	- check ‘TODO’
	- search and review remaining ‘LEFT OFF HERE’
	- review each external function algorithm / call stack
		- pay attention to uint type use (ie. uint32 vs 64 vs 256, etc.)
	- finalize / verify all external getter & setters needed
		- pay attention to returning structs properly (may need wrappers)
	DONE - finalize $CALL mint reward across all external functions (commented within)
	DONE - fix all LEFT OFF HERE ‘emit’ log integrations
	DONE - fix all LEFT OFF HERE ‘decimal’ integrations
	DONE - clean legacy code
	n/a - finalize integration for ‘_deductPrizePoolVoterFees’ -> ‘_deductFeePerc’
	DONE - finalize integration for ‘_deductArbExeFees’ -> ‘_deductFeePerc’
	DONE - finalize integration for ‘_deductMarketCloseFees’ -> ‘_deductFeePerc’
	DONE - finalize integration for ‘_deductVoterClaimFees’ -> ‘_deductFeePerc’
	DONE - finalize integration for ‘_deductMarketMakerFees’ -> ‘_deductFeePerc’
	DONE - finalize integration for ‘_deductPromoBuyFees’ -> ‘_deductFeePerc’
	DONE - maker score integration
		DONE - caller review of market results
		DONE - log (agree:disagree) of vote results in struct
		DONE - maintain agree:disagree ratio for maker score
	DONE - finalize integration for ‘exeArbPriceParityForTicket’
		DONE - need alt solution to bring down _ticket price (when input _ticket price >= $1)
		DONE - need alternate solution to bring down high alt_sum price (when input _ticket price < $1)
	DONE - finalize integration for ‘buyCallTicketWithPromoCode’
	DONE - finalize ‘_getMarketForTicket’
	DONE - finalized ‘_getCallTicketUsdTargetPrice’
	DONE - finalize ‘_calculateTokenToMint’
	DONE - finalize integration for ‘closeMarketCalls’
	DONE - finalize integration for ‘_getInitDexTokSupplyForUsdAmnt’
	DONE - refactor ‘creator’ to ‘maker’ globally
	DONE - finalize ‘castVoteFormarketTicket’
	DONE - finalize ‘closeMarketForTicket’
	DONE - finalize ‘claimVoterRewards’
	DONE - finalize ‘claimTicketRewards’
	DONE - add design support for functions …
		DONE - vote on market results
			DONE - checks for between dt vote start|end time
			DONE - allows 1 vote for $CALL held/locked before market create timestamp
			DONE - calc mark.usdVoterRewardPool in closeMarketForTicket
			DONE - mint $CALL earned to market maker in closeMarketForTicket
			DONE - calc voter distributions in closeMarketForTicket (maybe?)
		DONE - voter claim voter rewards earned
			DONE - maybe need tracking of voter fees owed
			DONE - usd vote reward = mark vote cnt * (usdVoterRewardPool / tot market win votes)
		DONE - caller claim winnings (claimTicketRewards)
			DONE - checks for after dt vote end time (or mark.live == false)
		DONE - caller claim losing $CALL (claimTicketRewards)
			DONE - checks for after dt vote end time (or mark.live == false)


COMPILE ERRORs_2:
Warning: Contract code size is 51559 bytes and exceeds 24576 bytes (a limit introduced in Spurious Dragon). This contract may not be deployable on Mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.
  --> /Users/greenhouse/devcrypto/git/callit/contracts/CallitFactory.sol:60:1:
   |
60 | contract CallitFactory is ERC20, Ownable {
   | ^ (Relevant source part starts here and spans across multiple lines).

Warning: Contract initcode size is 54160 bytes and exceeds 49152 bytes (a limit introduced in Shanghai). This contract may not be deployable on Mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.
  --> /Users/greenhouse/devcrypto/git/callit/contracts/CallitFactory.sol:60:1:
   |
60 | contract CallitFactory is ERC20, Ownable {
   | ^ (Relevant source part starts here and spans across multiple lines).


COMPILE ERRORs_1:
Warning: Contract code size is 55346 bytes and exceeds 24576 bytes (a limit introduced in Spurious Dragon). This contract may not be deployable on Mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.
  --> /Users/greenhouse/devcrypto/git/callit/contracts/CallitFactory.sol:58:1:
   |
58 | contract CallitFactory is ERC20, Ownable {
   | ^ (Relevant source part starts here and spans across multiple lines).

Warning: Contract initcode size is 58991 bytes and exceeds 49152 bytes (a limit introduced in Shanghai). This contract may not be deployable on Mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.
  --> /Users/greenhouse/devcrypto/git/callit/contracts/CallitFactory.sol:58:1:
   |
58 | contract CallitFactory is ERC20, Ownable {
   | ^ (Relevant source part starts here and spans across multiple lines).


COMPILE ERRORs_0:
Warning: Contract code size is 52357 bytes and exceeds 24576 bytes (a limit introduced in Spurious Dragon). This contract may not be deployable on Mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.

Warning: Contract initcode size is 56114 bytes and exceeds 49152 bytes (a limit introduced in Shanghai). This contract may not be deployable on Mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.

#================================================#
#================================================#